version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 0:0
    network_mode: 'host'
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/mount1:/media
    restart: 'unless-stopped'
